# Site settings
title: Pelican like
email: ibrother.linux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  写点什么好呢?
keywords: "ibrother, blog, linux, gentoo, vim, kde, program"
favicon: http://ibrother.qiniudn.com/favicon.ico
owner:
  name:           ibrother
twitter_username: IbrotherLinux
github_username:  ibrother
facebook: ibrother.me
google_plus:
instagram:
flickr:
weibo: 234684967

duoshuo_shortname: i2brother

# Links to include in footer navigation
# For external links add external: true
links:
  - title: 分类
    url: /categories
  - title: 标签
    url: /tags
  - title: 关于
    url: /about

# Links to dispaly in blogroll
rolls:
  - title: 码农圈
    url: https://coderq.com
  - title: 大哥哥
    url: http://ibrother.me
  - title: void
    url: http://voidy.gitcafe.com

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "<!--more-->"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/jekyll-pelican-theme" # the subpath of your site, e.g. /blog/
url: "http://staticblog.github.io" # the base hostname & protocol for your site

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /:categories/:title
paginate: 6
paginate_path: /page:num
timezone:      Asia/Shanghai

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

redcloth:
  hard_breaks: true

sass:
    sass_dir: _sass
    style: :compressed
